<div id="wrap-badges">
	<button id="badges" class="btn-drop">
		<i class="fa fa-bell-o fa-2x animated ringdong"></i>
		<p>20</p>
	</button>
	<ul id="drop-badges" class="drop-menu">
		<li><a href="lol.php">mnu1</a></li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
		<li>mnu2</li>
	</ul>
</div>